apiVersion: apps/v1
kind: Deployment
metadata:
  name: ec33nw-datahandler
  labels:
    app: ec33nw-datahandler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ec33nw-datahandler
  template:
    metadata:
      labels:
        app: ec33nw-datahandler
    spec:
      containers:
      - name: ec33nw-datahandler
        image: zedas/ec33nw-map-datahandler
        ports:
        - containerPort: 8080
        - containerPort: 8980
        imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: ec33nw-datahandler-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: resttestport
      protocol: TCP
      targetPort: 8080
    - port: 8980
      name: grcpport
      protocol: TCP
      targetPort: 8980
  selector:
    app: ec33nw-datahandler

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress
  annotations:
    dev.okteto.com/generate-host: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: this-name-does-not-matter
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ec33nw-datahandler-service
                port:
                  name: grcpport

